---
title: "Brief Introduction to Quarto Projects"
description: "This is a brief introduction to Quarto projects."
---

## About a Quarto Project

Quarto is a successor of R markdown. A Quarto project is defined by a `_quarto.yml` file and usually some Quarto markdown `.qmd` files. It can conveniently convert `.qmd` files into website, presentation or other formats. The output format is defined inside the `_quarto.yml` file. Multiple output format is allowed.

Quarto projects can be created and managed by [Quarto CLI tool](https://quarto.org/docs/get-started/).

::: {.callout-note}
Read more about [Quarto Projects](https://quarto.org/docs/projects/quarto-projects.html).
:::

## What can you do with Quarto?

Quarto is universal!

### Write PDF Documents

One of the most frequent use of Quarto is rendering PDF files for academic needs. [The official tutorial](https://quarto.org/docs/output-formats/pdf-basics.html) covers many aspects about this topic.

Additionally, you can use a LaTex template in a Quarto notebook for need of format. Here's [the official tutorial](https://quarto.org/docs/journals/templates.html) about this topic. Need inspirations? Check [the list of some letter examples](open-source-examples.html#letter-examples).

If you write journal papers, you can also consider [the built-in support of journals](https://quarto.org/docs/journals/formats.html).

### Create a Static Website

You can, of course, publish a website using Quarto, like how this website is rendered. Read more from [this introduction](website.html).

### Create a Word Document

Microsoft Word (.docx) format is also supported by Quarto. Read more from [this official tutorial](https://quarto.org/docs/output-formats/ms-word.html).

### Create a Diagram

It's possible to create simple but informative diagrams using Quarto. Read more from [this official tutorial](https://quarto.org/docs/authoring/diagrams.html)

### Presentation

Read more from [my page](presentation.html) about using Quarto to produce a nice presentation.
