project:
  type: website

website:
  title: "Learning R + Quarto"
  navbar:
    left:
      - text: Home
        href: content/index.qmd
      - text: R Topics
        menu:
          - text: Correlation And Linear Model
            href: content/r-topics/correlation-lm.qmd
          - text: Experiment Design
            href: content/r-topics/experiment-design.qmd
          - text: Basics of Tidyverse
            href: content/r-topics/tidyverse-basic.qmd
          - text: Tidyverse Exercise
            href: content/r-topics/tidyverse-exercise.qmd
          - text: Basics of ggplot2
            href: content/r-topics/ggplot2-basic.qmd
          - text: Pipe Operator
            href: content/r-topics/pipe-operator.qmd
          - text: Package Loading & Conflict Resolve
            href: content/r-topics/package-loading-conflict.qmd
          - text: Read And Export Data
            href: content/r-topics/read-export-data.qmd
          - text: Model Testing
            href: content/r-topics/model-testing.qmd
          - text: R Section Header
            href: content/r-topics/r-section-header.qmd
          - text: Further Resources
            href: content/further-resources.qmd
      - text: Quarto Topics
        menu:
          - text: Code Block
            href: content/quarto-topics/code-block.qmd
      - text: Examples
        menu:
          - text: One Way CRD Analysis
            href: content/examples/crd_mead1993.qmd
          - text: One Way RCBD Analysis
            href: content/examples/rcbd_clewerscarisbrick2001.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
