project:
  type: website

website:
  title: "Learning R + Quarto"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: R Topics
        menu:
          - text: Correlation And Linear Model
            href: content/r-topics/correlation-lm.qmd
          - text: Basics of Tidyverse
            href: content/r-topics/tidyverse-basic.qmd
          - text: Tidyverse Exercise
            href: content/r-topics/tidyverse-exercise.qmd
          - text: Basics of ggplot2
            href: content/r-topics/ggplot2-basic.qmd
          - text: Pipe Operator
            href: content/r-topics/pipe-operator.qmd
          - text: Package Loading & Conflict Resolve
            href: content/r-topics/package-loading-conflict.qmd
          - text: Read And Export Data
            href: content/r-topics/read-export-data.qmd
          - text: Model Testing
            href: content/r-topics/model-testing.qmd
          - text: Using Things about R and R Studio
            href: content/r-topics/useful-r-r_studio.qmd
      - text: Quarto Topics
        menu:
          - text: Code Block
            href: content/quarto-topics/code-block.qmd
          - text: Brief Introduction to Quarto Projects
            href: content/quarto-topics/quarto-projects.qmd
          - text: Writing a Website using Quarto
            href: content/quarto-topics/website.qmd
      - text: Experiment Designs
        menu:
          - text: Basics of Experiment Design
            href: content/experiment-designs/experiment-design-basic.qmd
          - text: One Way CRD Analysis
            href: content/experiment-designs/crd_mead1993.qmd
          - text: One Way RCBD Analysis
            href: content/experiment-designs/rcbd_clewerscarisbrick2001.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
