project:
  type: website

website:
  title: "Learning R Language"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Topics
        menu:
          - text: Correlation And Linear Model
            href: topics/correlation-lm.qmd
          - text: Experiment Design
            href: topics/experiment-design.qmd
          - text: Basics of Tidyverse
            href: topics/tidyverse-basic.qmd
          - text: Tidyverse Exercise
            href: topics/tidyverse-exercise.qmd
          - text: Basics of ggplot2
            href: topics/ggplot2-basic.qmd
          - text: Pipe Operator
            href: topics/pipe-operator.qmd
          - text: Package Loading & Conflict Resolve
            href: topics/package-loading-conflict.qmd
          - text: Read And Export Data
            href: topics/read-export-data.qmd
          - text: Model Testing
            href: topics/model-testing.qmd
          - text: R Section Header
            href: topics/r-section-header.qmd
      - text: Examples
        menu:
          - text: One Way CRD Analysis
            href: examples/crd_mead1993.qmd
          - text: One Way RCBD Analysis
            href: examples/rcbd_clewerscarisbrick2001.qmd
      - text: Further Resources
        href: further-resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
